name: Node.js Bot

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Start Bot
        run: node index.js
